# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoplaces_web', '0010_auto_20150119_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photocluster',
            name='points_month_1',
        ),
        migrations.RemoveField(
            model_name='photocluster',
            name='points_month_10',
        ),
        migrations.RemoveField(
            model_name='photocluster',
            name='points_month_11',
        ),
        migrations.RemoveField(
            model_name='photocluster',
            name='points_month_12',
        ),
        migrations.RemoveField(
            model_name='photocluster',
            name='points_month_2',
        ),
        migrations.RemoveField(
            model_name='photocluster',
            name='points_month_3',
        ),
        migrations.RemoveField(
            model_name='photocluster',
            name='points_month_4',
        ),
        migrations.RemoveField(
            model_name='photocluster',
            name='points_month_5',
        ),
        migrations.RemoveField(
            model_name='photocluster',
            name='points_month_6',
        ),
        migrations.RemoveField(
            model_name='photocluster',
            name='points_month_7',
        ),
        migrations.RemoveField(
            model_name='photocluster',
            name='points_month_8',
        ),
        migrations.RemoveField(
            model_name='photocluster',
            name='points_month_9',
        ),
        migrations.AddField(
            model_name='photocluster',
            name='points_month_10_relative',
            field=models.FloatField(default=0),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='photocluster',
            name='points_month_11_relative',
            field=models.FloatField(default=0),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='photocluster',
            name='points_month_12_relative',
            field=models.FloatField(default=0),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='photocluster',
            name='points_month_1_relative',
            field=models.FloatField(default=0),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='photocluster',
            name='points_month_2_relative',
            field=models.FloatField(default=0),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='photocluster',
            name='points_month_3_relative',
            field=models.FloatField(default=0),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='photocluster',
            name='points_month_4_relative',
            field=models.FloatField(default=0),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='photocluster',
            name='points_month_5_relative',
            field=models.FloatField(default=0),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='photocluster',
            name='points_month_6_relative',
            field=models.FloatField(default=0),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='photocluster',
            name='points_month_7_relative',
            field=models.FloatField(default=0),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='photocluster',
            name='points_month_8_relative',
            field=models.FloatField(default=0),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='photocluster',
            name='points_month_9_relative',
            field=models.FloatField(default=0),
            preserve_default=True,
        ),
    ]
